name: Release

# todo change
on: [push]
#on: [release]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, ubuntu-latest]
        target: [x86_64-unknown-linux-gnu, x86_64-apple-darwin, aarch64-apple-darwin]
        exclude:
        # Don't build linux targets on macos
        - os: macos-11
          target: x86_64-unknown-linux-gnu
        # Don't build darwin targets on ubuntu
        - os: ubuntu-latest
          target: x86_64-apple-darwin
        - os: ubuntu-latest
          target: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v3

      - name: get go
        uses: actions/setup-go@v4
        with:
          go-version: '1.16'

      - name: build bins
        run: go build -v ./...
