name: Release

on: [release]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - target: aarch64-apple-darwin
          os: darwin
          arch: arm64
        - target: x86_64-unknown-linux-gnu
          os: linux
          arch: amd64
    steps:
      - uses: actions/checkout@v3

      - name: get go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: build bins
        run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -v ./...
      - uses: Shopify/upload-to-release@master
        with:
          name: bigtable-emulator-${{ matrix.target }}
          path: bigtable-emulator
          repo-token: ${{ secrets.GITHUB_TOKEN }}
